delete repository workflow run: don't delete workflows that are canceled by admin

diff --git a/actions/delete_repository_workflow_run/action.yml b/actions/delete_repository_workflow_run/action.yml
--- a/actions/delete_repository_workflow_run/action.yml
+++ b/actions/delete_repository_workflow_run/action.yml
@@ -25,8 +25,23 @@ runs:
         fi
 
         for run_id in ${cancelled_run_ids[@]}; do
-          gh api \
-            --method DELETE \
+          job_details=$(gh api \
             -H "Accept: application/vnd.github+json" \
-            /repos/${{ github.repository }}/actions/runs/${run_id}
+            /repos/${{ github.repository }}/actions/runs/${run_id}/jobs | jq '.jobs')
+
+          job_details_len=$(jq '. | length' <<< $job_details)
+
+          if [[ $job_details_len < 1 ]]; then
+            echo "Job length is invalid"
+            exit 1
+          fi
+
+          first_job_conclusion=$(jq -r '.[0].conclusion' <<< $job_details)
+
+          if [[ $first_job_conclusion == 'cancelled' ]]; then
+            gh api \
+              --method DELETE \
+              -H "Accept: application/vnd.github+json" \
+              /repos/${{ github.repository }}/actions/runs/${run_id}
+          fi
         done
